### PR TITLE
CTP-2750 - checking if $USER->firstname is set before trying to use it

### PR DESCRIPTION
**Pull request by opitz**
This will prevent a core PHPUnit test from failing.

### CODE REVIEW

**Comment by aspark21** [comment]
Seems to me like this is addressing the symptom rather than the cause. Why isn't firstname set?

**Comment by opitz** [comment]
This is how $USER looks like when the test wants to use it:
`stdClass Object
(
    [id] => 0
    [mnethostid] => 1
    [sesskey] => AjGMw3QjHS
    [access] => Array
        (
            [ra] => Array
                (
                    [/1] => Array
                        (
                            [6] => 6
                        )

                )

            [time] => 1698329223
            [rsw] => Array
                (
                )

        )

    [enrol] => Array
        (
            [enrolled] => Array
                (
                )

            [tempguest] => Array
                (
                )

        )

)
`
As there is no proper user data set (yet?) trying to access the firstname fails.
Any ideas where to look?

**Comment by opitz** [comment]
@aspark21 I checked: at the time of the PHPUnit test (mod/bigbluebuttonbn/tests/local/extension_test.php) the global variable $USER is not properly set. Other blocks at time of init() show the same rudimentary $USER variable with this test.
block_my_feedback is the only block plugin I could find that is trying to use the user's firstname as part of the block title during init().
It may work fine under normal circumstances but it fails in a test scenario so it has to be fetched.

**Comment by aspark21** [comment]
https://tracker.moodle.org/browse/MDL-79857

https://github.com/ncstate-delta/moodle-mod_zoom/issues/534

is cron_setup_user() called in whichever unit test is causing this failure?

**Comment by opitz** [comment]
@aspark21 Here are my findings:
The issue remains when installing block_my_feedback into a vanilla MOODLE_403_STABLE.
No mod_zoom present, so it's unrelated (and appeqars in a core test where blocks are involved).

cron_user_setup() is deprecated but the successor cron::user_setup() is not called either from within the test.

It definitively looks like that at the time of the test the $USER global variable is just a stub and does not contain any user data (yet) - so trying to access the firstname during the test will fail.

**Comment by opitz** [comment]
@aydevworks @aspark21 I have now updated the catch for when the firstname is not set yet.
This will resolve the issue during installation (affects 4.x) and with the bigbluebutton test (affects 4.3+)
Please approve.

**Review by aspark21 — APPROVED** [review]

**Pull request merged**
